# Need to use sudo to run ansible commands.
ansible_ssh_user: ec2-user
ansible_become: yes

# Deploy openshift 3.3
deployment_type: openshift-enterprise
openshift_release: v3.3

# Have openshift master listen on standard https port 443
openshift_master_api_port: 443
openshift_master_console_port: 443

openshift_cloudprovider_aws_access_key: "{{ lookup('file', '/home/ec2-user/.aws/access-key-id') }}"
openshift_cloudprovider_aws_secret_key: "{{ lookup('file', '/home/ec2-user/.aws/access-secret-key') }}"

openshift_master_cluster_method: native
openshift_master_cluster_hostname: master.openshift-cluster
openshift_master_cluster_public_hostname: master.openshift-cluster

osm_default_node_selector: 'region=primary'

# AWS S3
# S3 bucket must already exist.
