openshift_hosted_registry_selector: 'region=infra'

# These configuration options requires openshift-ansible >= 3.3
openshift_hosted_registry_storage_kind: object
openshift_hosted_registry_storage_provider: s3
openshift_hosted_registry_storage_s3_accesskey: "{{ lookup('file', '/home/ec2-user/.aws/access-key-id') }}"
openshift_hosted_registry_storage_s3_secretkey: "{{ lookup('file', '/home/ec2-user/.aws/access-secret-key') }}"
openshift_hosted_registry_storage_s3_bucket: jkupferer-openshift-registry
openshift_hosted_registry_storage_s3_region: us-west-2
openshift_hosted_registry_storage_s3_chunksize: 26214400
openshift_hosted_registry_storage_s3_rootdirectory: /registry
openshift_hosted_registry_pullthrough: true
openshift_hosted_registry_acceptschema2: true
openshift_hosted_registry_enforcequota: true
